name: pierong-front
app: web
options:
    git:
        branch: master
        url: https://github.com/6floorpeople/pierong-front.git
    docbase: /build
    # env:
    #     - name: NODE_ENV
    #       value: production
    # install: npm ci --production
    # ports: 3000
    # start: npm start
